queue_rules:
  - name: hotfix
    allow_inplace_checks: true
    conditions:
      - label=hotfix
      - and: &CheckRuns
          - or:
              - -label=docker
              - check-success=docker-onpremise
    speculative_checks: 5
  - name: default
    allow_inplace_checks: true
    conditions:
      - and: *CheckRuns
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
    speculative_checks: 5
  - name: batch
    allow_inplace_checks: true
    conditions:
      - and: *CheckRuns
      - schedule=Mon-Fri 09:00-19:00[Europe/Paris]
    batch_size: 3
    batch_max_wait_time: 45min
    queue_branch_merge_method: fast-forward
    disallow_checks_interruption_from_queues:
      - default

pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=0"
    actions:
      queue:
  - name: Automatic merge on hotfix
    conditions:
      - "#approved-reviews-by>=0"
      - label=hotfix
    actions:
      queue:
        name: hotfix
        method: merge
        commit_message_template: null
  - name: automatic merge on batch label
    conditions:
      - "#approved-reviews-by>=0"
      - label=batch
    actions:
      queue:
        name: batch
        method: merge
        commit_message_template: null