queue_rules:
  - name: hotfix
    allow_inplace_checks: true
    conditions:
      - and: &CheckRuns
          - or:
              - -label=docker
              - check-success=docker-onpremise
          - check-success=semgrep
          - check-success=front (eslint)
          - check-success=front (test)
          - check-success=front (test:cf-page-worker)
          - check-success=front-component
          - check-success=front-e2e (1)
          - check-success=front-e2e (2)
          - check-success=front-e2e (3)
          - check-success=front-e2e (4)
          - check-success=front-e2e (5)
    speculative_checks: 5
  - name: default
    allow_inplace_checks: true
    conditions:
      - and: *CheckRuns
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
    speculative_checks: 5

pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=0"
    actions:
      queue: